* BACnet Help Logger
  The logger is a small utility designed to scan a BACnet network at
  regular interval and send back the data to a webserver (in this case
  https://bacnethelp.com).

* Immediate use
  If you have a typical BACnet network, you can simply download the
  logger package located in every project. Each one have the necessary
  configurations to match the said project.
  
  Once you have the package, unzip it in it's own directory and start
  the .jar file. You will require to have Java installed on your
  machine.

  The logger will work continuously until your machine is restarted.
  If you want to have a truly automated logging system, make sure the
  logger is started at every boot.

* Custom use
  We plan to make an installer to make this application easier to use,
  but meanwhile there's some manual work required, which we will see
  in a moment.

  The logger requires 2 files to work. First, the logger application
  itself. Second, the config file, which is nothing more than a
  clojure map. (If you don't know what a clojure map is, don't worry,
  it's extremely straightforward.)

** The config file
   This is the =config.cjm= file. You can open it with any text
   application, such as notepad.

   Starting from scratch?
   Simply create a new empty text file named =config.cjm=. (Beware if
   you are on windows; if your machine doesn't show the known
   extensions, you might end up with =config.cjm.txt=.)
   
   Here is an example of what should be in your file:
   #+BEGIN_SRC clojure :exports code
{:logger-password "1", 
 :project-id "5993529444ae4e7182a471b6"
 :broadcast-address "192.168.0.255"
 :port 47808}
   #+END_SRC

   The only necessary configurations are the :logger-password and
   the :project-id.

** The configurations
   Here are the possible configurations you can use in a config file:
   - :broadcast-address :: The logger will usually choose a broadcast
        address by itself, but you can manually assign one if needed.
   - :dest-port :: Your BACnet destination port
   - :logger-password :: Used to make sure there's no foreign data
        sent to your project.
   - :min and :max :: Used to limit the logging to a certain range of
                      devices.
   - :port :: Your local BACnet port. Some manufacturer send back
              packets to the same port they received them (which is
              wrong, but they still do). We recommend that if you
              change the ports, you make sure :dest-port and :port are
              the same.
   - :project-id :: This identifies to which project the data shall be
                    sent and saved. 
   - :scanner-id :: The logger BACnet device instance. Must be unique
                    on the network. Default to 1337.
* Fail-Safe
  In case of connection problem the logger will automatically keep the
  records locally as long as the connection isn't fixed. This insures
  that no data is ever lost.
* Troubleshooting
  To check if you have the correct configurations, we highly recommend
  that you test your network with the [[https://bacnethelp.com/how-to/scanner][/BACnet Help Network Scan/]]. If
  you can't see your network with it, you won't be able to use the
  logger.
* Open source
  Bacnet-logger is a small network scan utility built on top of the
  Serotonin BACnet4J GPLv3 library.
  (http://sourceforge.net/projects/bacnet4j/).

  Feel free to use/modify this application as you please. The source
  can be found [[https://github.com/Frozenlock/Bacnet-logger][here]]. If you want to make your own custom BACnet
  application, you should probably use BACnet4J directly, as it
  offers a wide range of functions unused in this application.

* License

  Copyright (C) 2012 Frozenlock

  GNU General Public License version 3.0 (GPLv3)
